---
- name: install buildbot dependencies
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python
    - python-pip
    - python-dev
    - git
    - python-setuptools

- name: install supervisor
  apt: pkg=supervisor state=latest
  when: buildbot_create_slave_supervisor

- name: install buildbot master
  easy_install: name=buildbot
  when: buildbot_create_master

- name: install buildbot slave
  easy_install: name=buildbot-slave
  when: buildbot_create_slave
